# Generated by Django 3.1.7 on 2021-04-13 12:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2021, 4, 13), message='Birthday cannot be in the future')])),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
